data "aws_ami" "worker_instance" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-2023*-x86_64"]
  }

  filter {
    name   = "architecture"
    values = ["x86_64"]
  }
}

data "aws_iam_policy_document" "ec2_assume_role" {
  statement {
    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }

    actions = ["sts:AssumeRole"]
  }
}

resource "aws_iam_role" "worker_role" {
  name               = "ec2-worker-role"
  assume_role_policy = data.aws_iam_policy_document.ec2_assume_role.json
}

resource "aws_iam_role_policy_attachment" "worker_role_policy" {
  role       = aws_iam_role.worker_role.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_policy" "read_parameter_store" {
  name        = "read_parameter_store"
  description = "IAM policy to read specific parameter store secrets"
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "ssm:Describe*",
        "ssm:Get*"
      ]
      Resource = [
        var.github_token_arn,
        var.discord_webhook_arn
      ]
    }]
  })
}

resource "aws_iam_role_policy_attachment" "worker_role_policy_ssm" {
  role       = aws_iam_role.worker_role.name
  policy_arn = aws_iam_policy.read_parameter_store.arn
}

resource "aws_iam_policy" "upload_oidc_files_s3" {
  name        = "upload_oidc_files_s3"
  description = "IAM policy to allow uploading OIDC files generated by the Kubernetes cluster to S3"
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "s3:PutObject"
      ]
      Resource = [
        "arn:aws:s3:::understand-the-wire-oidc-bucket/.well-known/openid-configuration",
        "arn:aws:s3:::understand-the-wire-oidc-bucket/openid/v1/jwks"
      ]
    }]
  })
}

resource "aws_iam_role_policy_attachment" "worker_role_policy_s3" {
  role       = aws_iam_role.worker_role.name
  policy_arn = aws_iam_policy.upload_oidc_files_s3.arn
}



resource "aws_iam_instance_profile" "worker_instance_profile" {
  name = "ec2-worker-instance-profile"
  role = aws_iam_role.worker_role.name
}

resource "aws_instance" "worker" {
  ami                  = data.aws_ami.worker_instance.id
  instance_type        = "m7i-flex.large"
  iam_instance_profile = aws_iam_instance_profile.worker_instance_profile.name

  # instance_market_options {
  #   market_type = "spot"
  #   spot_options {
  #     max_price = 0.01
  #   }
  # }

  primary_network_interface {
    network_interface_id = aws_network_interface.worker_instance_private_subnet_1.id
  }

  user_data = var.user_data

  tags = {
    managed_by : "Terraform"
  }
}

resource "aws_network_interface" "worker_instance_private_subnet_1" {
  subnet_id       = var.private_subnet_id
  description     = "Connecting the worker instance to the private subnet"
  private_ips     = ["10.50.1.10"]
  security_groups = [var.private_ec2_sg]
}