resource "aws_iam_role" "control_plane_node_role" {
  name               = "${var.name_prefix}-control-plane-node-role"
  assume_role_policy = data.aws_iam_policy_document.ec2_assume_role.json
}

data "aws_iam_policy_document" "ec2_assume_role" {
  statement {
    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }

    actions = ["sts:AssumeRole"]
  }
}

resource "aws_iam_role_policy_attachment" "ssm_policy_attachment" {
  role       = aws_iam_role.control_plane_node_role.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_policy" "read_parameter_store" {
  name        = "${var.name_prefix}-read-parameter-store"
  description = "IAM policy to read specific parameter store secrets"
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "ssm:Describe*",
        "ssm:Get*"
      ]
      Resource = [
        var.parameter_store_secrets_arn.discord_webhook,
        var.parameter_store_secrets_arn.github_token
      ]
    }]
  })
}

resource "aws_iam_role_policy_attachment" "read_param_store_attachment" {
  role       = aws_iam_role.control_plane_node_role.name
  policy_arn = aws_iam_policy.read_parameter_store.arn
}

resource "aws_iam_policy" "upload_oidc_files_s3" {
  name        = "${var.name_prefix}-upload-oidc-files-s3"
  description = "IAM policy to allow uploading OIDC files generated by the Kubernetes cluster to S3"
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "s3:PutObject"
      ]
      Resource = [
        "${var.oidc_bucket.arn}/.well-known/openid-configuration",
        "${var.oidc_bucket.arn}/openid/v1/jwks"
      ]
    }]
  })
}

resource "aws_iam_role_policy_attachment" "put_oidc_bucket_attachemnt" {
  role       = aws_iam_role.control_plane_node_role.name
  policy_arn = aws_iam_policy.upload_oidc_files_s3.arn
}