apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externalsecret-grafana
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameterstore
    kind: ClusterSecretStore
  target:
    name: grafana
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: ${parameter_name_prefix}/grafana/username
  - secretKey: password
    remoteRef:
      key: ${parameter_name_prefix}/grafana/password
