apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externalsecret-github
  namespace: flux-system  # Flux ImageRepositories need this secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameterstore
    kind: ClusterSecretStore
  target:
    name: github
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "Alon Kopilov",
                "password": "{{ .packages_token }}",
                "auth": "{{ printf "%s:%s" "Alon Kopilov" .packages_token | b64enc }}"
              }
            }
          }
  data:
  - secretKey: packages_token
    remoteRef:
      key: ${parameter_name_prefix}/github/packages-token
