apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: controllers
  namespace: flux-system
spec:
  interval: 10m

  path: ./k8s/infrastructure/controllers

  prune: true

  # Grafana in the 'kube-prometheus-stack' has to use a secret,
  # that is only available after 'external-secrets' is installed.  
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: external-secrets
      namespace: flux-system

  sourceRef:
    kind: GitRepository
    name: flux-system