apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: understand-the-wire
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: trainingdemos/k8s-frontend-podinfo:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 128Mi
            cpu: 40m
