apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: understand-the-wire
data:
  AWS_ROLE_ARN: arn:aws:iam::${account_id}:role/utw-${environment}-understand-the-wire-server-sa-role
  AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/aws/token
  AWS_REGION: ${aws_region}
  AWS_DEFAULT_REGION: ${aws_region}
