apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: understand-the-wire
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: sa
      containers:
      - name: server
        image: ghcr.io/alonkopilov/understand-the-wire-server-prod:20260826-111616 # {"$imagepolicy": "flux-system:server-imagepolicy"}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 128Mi
            cpu: 40m
