apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externalsecret-grafana
  namespace: altshare
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameterstore
  target:
    name: grafana
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: /production/grafana/username
  - secretKey: password
    remoteRef:
      key: /production/grafana/password
