apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-ingress
  namespace: understand-the-wire
spec:
  rules:
  - http:
      paths:
      - path: /health
        pathType: Exact
        backend:
          service:
            name: service
            port:
              number: 80