apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-parameterstore
  namespace: external-secrets
spec:
  provider:
    aws:
      service: ParameterStore
      role: arn:aws:iam::744092294111:role/external-secrets-external-secrets-role
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
