name: Apply Infrastructure

on:
  workflow_dispatch:

env:
  ACCOUNT_ID: "744092294111"
  REGION: eu-central-1
  ENVIRONMENT: prod

jobs:
  apply-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ env.REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.16.1"

      - name: Fetch Secrets from AWS SSM Parameter Store
        run: |
          TOKEN=$(aws ssm get-parameter \
            --name "/utw/global/cloudflare/api-token" \
            --with-decryption \
            --query "Parameter.Value" \
            --output text)
          echo "::add-mask::$TOKEN"
          echo "TF_VAR_cloudflare_api_token=$TOKEN" >> "$GITHUB_ENV"

      - name: Apply Bootstrap
        run: |
          cd $GITHUB_WORKSPACE/infrastructure/bootstrap/${{ env.ENVIRONMENT }}
          terraform init
          terraform validate
          terraform apply -auto-approve -input=false

      - name: Apply Environment
        run: |
          cd $GITHUB_WORKSPACE/infrastructure/environments/${{ env.ENVIRONMENT }}
          terraform init
          terraform validate
          terraform apply -auto-approve -input=false
          